import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { AIInsight } from "@/data/salesData";
import { TrendingUp, AlertTriangle, Lightbulb } from "lucide-react";
import { cn } from "@/lib/utils";

interface AIInsightsPanelProps {
  insights: AIInsight[];
}

export const AIInsightsPanel = ({ insights }: AIInsightsPanelProps) => {
  const getInsightIcon = (type: AIInsight['type']) => {
    switch (type) {
      case 'trend':
        return <TrendingUp className="h-5 w-5 text-primary" />;
      case 'alert':
        return <AlertTriangle className="h-5 w-5 text-warning" />;
      case 'opportunity':
        return <Lightbulb className="h-5 w-5 text-success" />;
    }
  };

  const getImpactBadge = (impact: AIInsight['impact']) => {
    const variants = {
      high: "bg-destructive/10 text-destructive border-destructive/20",
      medium: "bg-warning/10 text-warning border-warning/20",
      low: "bg-muted text-muted-foreground border-border",
    };

    return (
      <Badge variant="outline" className={cn("text-xs", variants[impact])}>
        {impact.toUpperCase()} IMPACT
      </Badge>
    );
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Lightbulb className="h-5 w-5 text-primary" />
          AI-Powered Insights
        </CardTitle>
        <CardDescription>
          Natural language analysis and predictions generated by advanced forecasting models
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {insights.map((insight) => (
          <div
            key={insight.id}
            className="rounded-lg border bg-card p-4 transition-colors hover:bg-accent/50"
          >
            <div className="flex items-start gap-3">
              <div className="mt-1">{getInsightIcon(insight.type)}</div>
              <div className="flex-1 space-y-2">
                <div className="flex items-start justify-between gap-2">
                  <h4 className="font-semibold text-foreground">{insight.title}</h4>
                  {getImpactBadge(insight.impact)}
                </div>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  {insight.description}
                </p>
                {insight.fiscalYear && (
                  <div className="flex items-center gap-2 text-xs text-muted-foreground">
                    <span className="font-medium">Target Year:</span>
                    <Badge variant="secondary" className="text-xs">
                      {insight.fiscalYear}
                    </Badge>
                  </div>
                )}
              </div>
            </div>
          </div>
        ))}
      </CardContent>
    </Card>
  );
};
